# Generated by Django 3.2.20 on 2023-07-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.CharField(max_length=255)),
                ('quantite', models.CharField(max_length=255)),
            ],
        ),
    ]
